#!/bin/sh

# Check if the "lua" executable is available
if ! command -v lua >/dev/null 2>&1; then
    echo "Error: 'lua' is not installed. Please install Lua to proceed."
    exit 1
fi

# Run the Lua script and pass all arguments to it
cd /usr/local/share/setup-ninja
lua setup-ninja.lua "$@"

